### ISSUE TITLE
About model.py code

### ISSUE THREAD

**Issue by DuanhaoranCC** [hengruizhang98/GRAND#1]
Hello, dear author, I would like to ask why I should multiply with 1-p when I predict in the deleted node characteristic function
In order to maintain expectations during training, I should multiply $1/1-p$?Thank you!
`def drop_node(feats, drop_rate, training):
    
    n = feats.shape[0]
    drop_rates = th.FloatTensor(np.ones(n) * drop_rate)
    
    if training:
            
        masks = th.bernoulli(1. - drop_rates).unsqueeze(1)
        feats = masks.to(feats.device) * feats
        
    else:
        feats = feats * (1. - drop_rate)

    return feats`

**Comment by hengruizhang98** [comment]
This is to make sure that the input features of training data and testing data are at the same scale (in training, we randomly drop a fraction of drop features).
